services:
  website:
    image: ghcr.io/poewa/bolletrold.dk:latest
    container_name: website
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolle.rule=Host(`bolletrold.dk`) || Host(`www.bolletrold.dk`)"
      - "traefik.http.routers.bolle.entrypoints=websecure"
      - "traefik.http.routers.bolle.tls.certresolver=cloudflare"
      # This line forces a wildcard cert for the new domain
      - "traefik.http.routers.bolle.tls.domains[0].main=bolletrold.dk"
      - "traefik.http.routers.bolle.tls.domains[0].sans=*.bolletrold.dk"
      # Explicitly tell Traefik to use the HTTP scheme
      - "traefik.http.services.bolle.loadbalancer.server.port=80"
      - "traefik.http.services.bolle.loadbalancer.server.scheme=http"
    networks:
      - proxy

networks:
  proxy:
    external: true